BULK INSERT Employee
FROM 'C:\backup\ZIPPLO TEST DATA\Employee.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', CODEPAGE = '65001');

BULK INSERT Customer
FROM 'C:\backup\ZIPPLO TEST DATA\Customer.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', CODEPAGE = '65001');

BULK INSERT Equipment
FROM 'C:\backup\ZIPPLO TEST DATA\Equipment.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', CODEPAGE = '65001');

BULK INSERT RentalPlace
FROM 'C:\backup\ZIPPLO TEST DATA\Rental_Place.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', CODEPAGE = '65001');

BULK INSERT EquipmentUnit
FROM 'C:\backup\ZIPPLO TEST DATA\Equipment_Unit.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', CODEPAGE = '65001');

BULK INSERT RentalTransaction
FROM 'C:\backup\ZIPPLO TEST DATA\Rental_Transaction.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', CODEPAGE = '65001');